eatsj_web/api/urls.py
from django.urls import path
# from rest_framework.authtoken import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

from .views import UserRecordView


app_name = 'api'

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_refresh'),
    path('user/', UserRecordView.as_view(), name='users'),
]

eatsj_web/eatsj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('web.urls')),
    path('api/', include('api.urls')),
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

eatsj_web/web/urls.py
from django.urls import path, include

from . import views


app_name = "eatsj"


urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('leaderboard', views.LeaderboardView.as_view(), name="leaderboard"),
    path('histories', views.HistoriesListView.as_view(), name="history_list"),

    path('auth/', include([
        path('account/', views.AccountView.as_view(), name='account'),
        path('signin/', views.SigninView.as_view(), name="signin"),
        path('signout/', views.signout, name="signout"),
    ])),

    path('users/', include([
        path('', views.UserListView.as_view(), name="user_list"),
        path('save/', views.UserCreateView.as_view(), name="user_create"),
        path('<pk>/details/', views.UserDetailsView.as_view(), name="user_details"),
        path('<pk>/delete/', views.user_delete_view, name="user_delete"),
    ])),

    path('products/', include([
        path('menus/', include([
            path('', views.ProductsMenuListView.as_view(), name="products_menu_list"),
            path('save/', views.ProductsMenuCreateView.as_view(), name="products_menu_create"),
        ])),
        path('foods/', include([
            path('', views.ProductsFoodListView.as_view(), name="products_food_list"),
            path('save/', views.ProductsFoodCreateView.as_view(), name="products_food_create"),
            path('<pk>/details/', views.ProductsFoodDetailsView.as_view(), name="products_food_details"),
            path('<pk>/delete/', views.product_food_delete_view, name="products_food_delete"),
        ])),
        path('drinks/', include([
            path('', views.ProductsDrinkListView.as_view(), name="products_drink_list"),
            path('save/', views.ProductsDrinkCreateView.as_view(), name="products_drink_create"),
            path('<pk>/details/', views.ProductsDrinkDetailsView.as_view(), name="products_drink_details"),
            path('<pk>/delete/', views.product_drink_delete_view, name="products_drink_delete"),
        ])),
    ])),

    path('orders/', include([
        path('', views.OrdersListView.as_view(), name="order_list")
    ])),

]

eatsj_web/web/templates/pages/products/drink_create.html
{% extends 'layouts/__products.html' %}

{% block title %} Ajout Boisson {% endblock %}

{% block personal_head %}
    {% include 'shared/_css_importfile.html' %}
    {% include 'shared/_js_importfile.html' %}
{% endblock personal_head %}

{% block topbar %} {% include 'shared/_topbar.html' with current="products" title="products_drink" %} {% endblock %}

{% block breadcrumb %} {% include 'shared/_breadcrumb.html' with current='products' title='drinks_create' %} {% endblock breadcrumb %}

{% block main %}
    <h1 class="h2">Ajouter une nouvelle boisson</h1>


    <form class="t-grey mt-5" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        
        {% if form.errors %}
            <div class="alert warning mb-5">
                {% for error in form.errors %}
                    <div>{{ error }}</div>
                {% endfor %}
            </div>
        {% endif %}

        <div class="grid of-2 gap-3">
            <div class="cell field">
                {{ form.name }}
                <div class="field-label">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{ form.price_init }}
                <div class="field-label">
                    <label for="{{ form.price_init.id_for_label }}">{{ form.price_init.label_tag }}</label>
                </div>
            </div>
            <div class="cell field colspan-all">
                {{ form.image }}
                <div class="field-label">
                    <label for="{{ form.image.id_for_label }}">{{ form.image.label_tag }}</label>
                </div>
            </div>
            <div class="cell colspan-all field">
                {{ form.nbr_liter }}
                <div class="field-label">
                    <label for="{{ form.nbr_liter.id_for_label }}">{{ form.nbr_liter.label_tag }}</label>
                </div>
            </div>
        </div>
        
        <div class="text-center mt-5">
            <button type="submit" class="btn primary t-white">Enregistrer</button>
        </div>
    </form>

    <!-- <script>
        FilePond.registerPlugin(
            FilePondPluginImageCrop,
            FilePondPluginImagePreview,
            FilePondPluginImageResize,
            FilePondPluginImageTransform
        );

        const inputElement = document.querySelector('input[type="file"]');
        const pond = FilePond.create(inputElement, {
            imageCropAspectRatio: 1,
            imageResizeTargetWidth: 500,
            imageResizeTargetHeight: 300,
            imageResizeMode: 'contain',
            imageTransformVariants: {
                thumb_medium_: transforms => {
                    transforms.resize.size.width = 512;

                    // this will be a landscape crop
                    transforms.crop.aspectRatio = .5;

                    return transforms;
                }
            },
            onaddfile: (err, fileItem) => {
                console.log(err, fileItem.getMetadata('resize'));
            },
            onpreparefile: (fileItem, outputFiles) => {
                outputFiles.forEach(output => {
                    const img = new Image();
                    img.src = URL.createObjectURL(output.file);
                    console.log(img)
                    // document.body.appendChild(img);
                })
            }
        });
    </script> -->
{% endblock %}

eatsj_web/web/templates/pages/products/drink_details.html
{% extends 'layouts/__products.html' %}

{% block title %} Détails Boisson {% endblock %}

{% block personal_head %}
    <!-- {% include 'shared/_css_importfile.html' %}
    {% include 'shared/_js_importfile.html' %} -->
{% endblock personal_head %}

{% block topbar %} {% include 'shared/_topbar.html' with current="products" title="products_drink" %} {% endblock %}

{% block breadcrumb %} {% include 'shared/_breadcrumb.html' with current='products' title='drinks_details' %} {% endblock breadcrumb %}

{% block main %}
    <h1 class="h2">Détails du {{ object.name }}</h1>


    <form class="t-grey mt-5" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {% if form.errors %}
            <div class="alert warning mb-5">
                {% for error in form.errors %}
                    <div>{{ error }}</div>
                {% endfor %}
            </div>
        {% endif %}

        <div class="grid of-2 gap-3">
            <div class="cell field">
                {{ form.name }}
                <div class="field-label">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{ form.price_init }}
                <div class="field-label">
                    <label for="{{ form.price_init.id_for_label }}">{{ form.price_init.label_tag }}</label>
                </div>
            </div>
            <div class="cell field colspan-all">
                {{ form.image }}
                <div class="field-label">
                    <label for="{{ form.image.id_for_label }}">{{ form.image.label_tag }}</label>
                </div>
            </div>
            <div class="cell colspan-all field">
                {{ form.description }}
                <div class="field-label">
                    <label for="{{ form.description.id_for_label }}">{{ form.description.label_tag }}</label>
                </div>
            </div>
        </div>
        
        <div class="text-center mt-5">
            <div class="group">
                <button type="button" class="btn info link">Cliquez ici pour modifier</button>
                <button type="submit" class="btn primary t-white" disabled>Modifier</button>
            </div>
        </div>
    </form>

    <!-- <script>
        FilePond.registerPlugin(
            FilePondPluginImageCrop,
            FilePondPluginImagePreview,
            FilePondPluginImageResize,
            FilePondPluginImageTransform
        );

        const inputElement = document.querySelector('input[type="file"]');
        const pond = FilePond.create(inputElement, {
            imageCropAspectRatio: 1,
            imageResizeTargetWidth: 500,
            imageResizeTargetHeight: 300,
            imageResizeMode: 'contain',
            imageTransformVariants: {
                thumb_medium_: transforms => {
                    transforms.resize.size.width = 512;

                    // this will be a landscape crop
                    transforms.crop.aspectRatio = .5;

                    return transforms;
                }
            },
            onaddfile: (err, fileItem) => {
                console.log(err, fileItem.getMetadata('resize'));
            },
            onpreparefile: (fileItem, outputFiles) => {
                outputFiles.forEach(output => {
                    const img = new Image();
                    img.src = URL.createObjectURL(output.file);
                    console.log(img)
                    // document.body.appendChild(img);
                })
            }
        });
    </script> -->
{% endblock %}

eatsj_web/web/templates/pages/products/drinks.html
{% extends 'layouts/__products.html' %}

{% load static %}
{% load humanize %}

{% block title %} Boissons {% endblock %}

{% block topbar %} {% include 'shared/_topbar.html' with current="products" title="products_drink" %} {% endblock %}

{% block breadcrumb %} {% include 'shared/_breadcrumb.html' with current='products' title='drinks' %} {% endblock breadcrumb %}

{% block main %}
    <div class="row">
        <div class="col">
            <h1 class="h2">Boissons</h1>
        </div>
        <div class="col text-right">
            <a href="{% url 'eatsj:products_drink_create' %}" class="btn primary">
                <span class="icon">
                    <i class="material-icons">add</i>
                </span>&nbsp;
                <span>Ajouter</span>
            </a>
        </div>
    </div>

    <div class="grid of-sm-1 of-md-2 of-lg-3 of-xl-5 gap-2">
        {% for drink in object_list %}
            <div class="cell card">
                <div class="card-item product_image" style="background-image: url('{% if drink.image %} {{ drink.image.url }} {% else %} {% static '/img/default-food-image.jpg' %}  {% endif %}')">
                    <div class="product_content t-white">
                        <div class="title"><span>{{ drink.name }}</span> <span>({{ drink.nbr_liter|intcomma }} L)</span></div>
                        <div class="subtitle">{{ drink.price_init|intcomma }} F CFA</div>
                    </div>
                </div>
                <div class="card-item display as-flex justify-content-end">
                    <a href="{% url 'eatsj:products_drink_delete' pk=drink.pk %}" class="btn link transparent no-border t-danger p-0">
                        <span class="icon"><i class="material-icons h3">delete</i></span>
                    </a>
                    <a href="{% url 'eatsj:products_drink_details' pk=drink.pk %}" class="btn link transparent no-border t-info p-0 ml-1">
                        <span class="icon"><i class="material-icons h3">visibility</i></span>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

eatsj_web/web/templates/pages/products/food_create.html
{% extends 'layouts/__products.html' %}

{% block title %} Ajout Plat {% endblock %}

{% block personal_head %}
    <!-- {% include 'shared/_css_importfile.html' %}
    {% include 'shared/_js_importfile.html' %} -->
{% endblock personal_head %}

{% block topbar %} {% include 'shared/_topbar.html' with current="products" title="products_food" %} {% endblock %}

{% block breadcrumb %} {% include 'shared/_breadcrumb.html' with current='products' title='foods_create' %} {% endblock breadcrumb %}

{% block main %}
    <h1 class="h2">Ajouter un nouveau plat</h1>


    <form class="t-grey mt-5" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- {{ form }} -->

        
        {% if form.errors %}
            <div class="alert warning mb-5">
                {% for error in form.errors %}
                    <div>{{ error }}</div>
                {% endfor %}
            </div>
        {% endif %}

        <div class="grid of-2 gap-3">
            <div class="cell field">
                {{ form.name }}
                <div class="field-label">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{ form.price_init }}
                <div class="field-label">
                    <label for="{{ form.price_init.id_for_label }}">{{ form.price_init.label_tag }}</label>
                </div>
            </div>
            <div class="cell field colspan-all">
                {{ form.image }}
                <div class="field-label">
                    <label for="{{ form.image.id_for_label }}">{{ form.image.label_tag }}</label>
                </div>
            </div>
            <div class="cell colspan-all field">
                {{ form.description }}
                <div class="field-label">
                    <label for="{{ form.description.id_for_label }}">{{ form.description.label_tag }}</label>
                </div>
            </div>
        </div>
        
        <div class="text-center mt-5">
            <button type="submit" class="btn primary t-white">Enregistrer</button>
        </div>
    </form>

    <!-- <script>
        FilePond.registerPlugin(
            FilePondPluginImageCrop,
            FilePondPluginImagePreview,
            FilePondPluginImageResize,
            FilePondPluginImageTransform
        );

        const inputElement = document.querySelector('input[type="file"]');
        const pond = FilePond.create(inputElement, {
            imageCropAspectRatio: 1,
            imageResizeTargetWidth: 500,
            imageResizeTargetHeight: 300,
            imageResizeMode: 'contain',
            imageTransformVariants: {
                thumb_medium_: transforms => {
                    transforms.resize.size.width = 512;

                    // this will be a landscape crop
                    transforms.crop.aspectRatio = .5;

                    return transforms;
                }
            },
            onaddfile: (err, fileItem) => {
                console.log(err, fileItem.getMetadata('resize'));
            },
            onpreparefile: (fileItem, outputFiles) => {
                outputFiles.forEach(output => {
                    const img = new Image();
                    img.src = URL.createObjectURL(output.file);
                    console.log(img)
                    // document.body.appendChild(img);
                })
            }
        });
    </script> -->
{% endblock %}

eatsj_web/web/templates/pages/products/food_details.html
{% extends 'layouts/__products.html' %}

{% block title %} Détails Plat {% endblock %}

{% block personal_head %}
    <!-- {% include 'shared/_css_importfile.html' %}
    {% include 'shared/_js_importfile.html' %} -->
{% endblock personal_head %}

{% block topbar %} {% include 'shared/_topbar.html' with current="products" title="products_food" %} {% endblock %}

{% block breadcrumb %} {% include 'shared/_breadcrumb.html' with current='products' title='foods_details' %} {% endblock breadcrumb %}

{% block main %}
    <h1 class="h2">Détails du {{ object.name }}</h1>


    <form class="t-grey mt-5" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- {{ form }} -->

        
        {% if form.errors %}
            <div class="alert warning mb-5">
                {% for error in form.errors %}
                    <div>{{ error }}</div>
                {% endfor %}
            </div>
        {% endif %}

        <div class="grid of-2 gap-3">
            <div class="cell field">
                {{ form.name }}
                <div class="field-label">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{ form.price_init }}
                <div class="field-label">
                    <label for="{{ form.price_init.id_for_label }}">{{ form.price_init.label_tag }}</label>
                </div>
            </div>
            <div class="cell field colspan-all">
                {{ form.image }}
                <div class="field-label">
                    <label for="{{ form.image.id_for_label }}">{{ form.image.label_tag }}</label>
                </div>
            </div>
            <div class="cell colspan-all field">
                {{ form.description }}
                <div class="field-label">
                    <label for="{{ form.description.id_for_label }}">{{ form.description.label_tag }}</label>
                </div>
            </div>
        </div>
        
        <div class="text-center mt-5">
            <div class="group">
                <button type="button" class="btn info link">Cliquez ici pour modifier</button>
                <button type="submit" class="btn primary t-white" disabled>Modifier</button>
            </div>
        </div>
    </form>

    <!-- <script>
        FilePond.registerPlugin(
            FilePondPluginImageCrop,
            FilePondPluginImagePreview,
            FilePondPluginImageResize,
            FilePondPluginImageTransform
        );

        const inputElement = document.querySelector('input[type="file"]');
        const pond = FilePond.create(inputElement, {
            imageCropAspectRatio: 1,
            imageResizeTargetWidth: 500,
            imageResizeTargetHeight: 300,
            imageResizeMode: 'contain',
            imageTransformVariants: {
                thumb_medium_: transforms => {
                    transforms.resize.size.width = 512;

                    // this will be a landscape crop
                    transforms.crop.aspectRatio = .5;

                    return transforms;
                }
            },
            onaddfile: (err, fileItem) => {
                console.log(err, fileItem.getMetadata('resize'));
            },
            onpreparefile: (fileItem, outputFiles) => {
                outputFiles.forEach(output => {
                    const img = new Image();
                    img.src = URL.createObjectURL(output.file);
                    console.log(img)
                    // document.body.appendChild(img);
                })
            }
        });
    </script> -->
{% endblock %}

eatsj_web/web/templates/pages/products/foods.html
{% extends 'layouts/__products.html' %}
{% load static %}
{% load humanize %}

{% block title %} Plats {% endblock %}

{% block topbar %} {% include 'shared/_topbar.html' with current="products" title="products_food" %} {% endblock %}

{% block breadcrumb %} {% include 'shared/_breadcrumb.html' with current='products' title='foods' %} {% endblock breadcrumb %}

{% block main %}
    <div class="row">
        <div class="col">
            <h1 class="h2">Plats</h1>
        </div>
        <div class="col text-right">
            <a href="{% url 'eatsj:products_food_create' %}" class="btn primary">
                <span class="icon">
                    <i class="material-icons">add</i>
                </span>&nbsp;
                <span>Ajouter</span>
            </a>
        </div>
    </div>

    <div class="grid of-sm-1 of-md-2 of-lg-3 of-xl-5 gap-2">
        {% for food in object_list %}
            <div class="cell card ">
                <div class="card-item product_image" style="background-image: url('{% if food.image %} {{ food.image.url }} {% else %} {% static '/img/default-food-image.jpg' %}  {% endif %}')">
                    <div class="product_content t-white">
                        <div class="title">{{ food.name }}</div>
                        <div class="subtitle">{{ food.price_init|intcomma }} F CFA</div>
                    </div>
                </div>
                <div class="card-item text-justify">
                    {{ food.description }}
                </div>
                <div class="card-item display as-flex justify-content-end">
                    <a href="{% url 'eatsj:products_food_delete' pk=food.pk %}" class="btn link transparent no-border t-danger p-0">
                        <span class="icon"><i class="material-icons h3">delete</i></span>
                    </a>
                    <a href="{% url 'eatsj:products_food_details' pk=food.pk %}" class="btn link transparent no-border t-info p-0 ml-1">
                        <span class="icon"><i class="material-icons h3">visibility</i></span>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

eatsj_web/web/templates/pages/products/menus.html
{% extends 'layouts/__products.html' %}

{% block title %} Menus {% endblock %}

{% block topbar %} {% include 'shared/_topbar.html' with current="products" title="products_menu" %} {% endblock %}

{% block breadcrumb %} {% include 'shared/_breadcrumb.html' with current='products' %} {% endblock breadcrumb %}

{% block main %}
    <div class="row">
        <div class="col">
            <h1 class="h2">Menu</h1>
        </div>
        <div class="col text-right">
            <a href="{% url 'eatsj:products_menu_create' %}" class="btn secondary">
                <span class="icon">
                    <i class="material-icons">add</i>
                </span>&nbsp;
                <span>Créer le menu du jour</span>
            </a>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table striped centered">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Nombre de plat vendu</th>
                    <th>Nombre de boisson vendu</th>
                    <th>Gains (F CFA)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>04/01/2021</td>
                    <td>15/20</td>
                    <td>20/20</td>
                    <td>20 000</td>
                    <td>
                        <div class="group">
                            <button class="btn link danger size-sm">Supprimer</button>
                            <button class="btn info size-sm">Détails</button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

eatsj_web/web/templates/pages/products/menus_create.html
{% extends 'layouts/__products.html' %}

{% block title %} Créer menu jour {% endblock %}

{# % block personal_head %}
{% endblock personal_head % #}

{% block topbar %} {% include 'shared/_topbar.html' with current="products" title="products_menu" %} {% endblock %}

{% block breadcrumb %} {% include 'shared/_breadcrumb.html' with current='products' title="menus_create" %} {% endblock breadcrumb %}

{% block main %}
    <h1 class="h2">Ajouter Menu du jour</h1>
    <div class="form_wrapper">
        <fieldset class="msf_hide">
            <h2>The first form</h2>
          <div>
              <input type="text" name="firstname" placeholder="First Name">
            <input type="text" name="lastname" placeholder="Last Name">
          </div>
          <div>
            <input type="email" name="email" placeholder=" Your Email">
          </div>
            <input type="button" name="back" value="Back"  onclick="msf_btn_back()">
              <input type="button" name="next" value="Next"  onclick="msf_btn_next()">
          <div class="msf_bullet_o"></div>
          <div class="msf_line"></div>
        </fieldset>
        
        <fieldset class="msf_hide">
            <h2>This is form 2</h2>
            <input type="text" name="school" placeholder="School">
            <input type="date" name="date" placeholder="Birthdate">
          <div>
            <input type="radio" name="gender" value="male" checked> Male<br>
            <input type="radio" name="gender" value="female"> Female<br>
            <input type="radio" name="gender" value="other"> Other
          </div>
          <input type="button" name="back" value="Back"  onclick="msf_btn_back()">
            <input type="button" name="next" value="Next"  onclick="msf_btn_next()">
          <div class="msf_bullet_o"></div>
          <div class="msf_line"></div>
        </fieldset>
        
        <fieldset class="msf_hide">
            <h2>The last form</h2>
            <input type="text" name="name" placeholder="Name">
            <input type="email" name="email" placeholder="Email">
          <input type="button" name="back" value="Back"  onclick="msf_btn_back()">
          <input type="button" name="next" value="Next"  onclick="msf_btn_next()">
            <input type="submit" name="submit" value="Submit Now!" onclick="">
          <div class="msf_bullet_o"></div>
          <div class="msf_line"></div>
        </fieldset>
        </div>


    <!-- <form class="t-grey mt-5" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {% if form.errors %}
            <div class="alert warning mb-5">
                {% for error in form.errors %}
                    <div>{{ error }}</div>
                {% endfor %}
            </div>
        {% endif %}

        <div class="grid of-2 gap-3">
            <div class="cell field">
                {{ form.name }}
                <div class="field-label">
                    <label for="{{ form.name.id_for_label }}">{{ form.name.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{ form.price_init }}
                <div class="field-label">
                    <label for="{{ form.price_init.id_for_label }}">{{ form.price_init.label_tag }}</label>
                </div>
            </div>
            <div class="cell field colspan-all">
                {{ form.image }}
                <div class="field-label">
                    <label for="{{ form.image.id_for_label }}">{{ form.image.label_tag }}</label>
                </div>
            </div>
            <div class="cell colspan-all field">
                {{ form.description }}
                <div class="field-label">
                    <label for="{{ form.description.id_for_label }}">{{ form.description.label_tag }}</label>
                </div>
            </div>
        </div>
        
        <div class="text-center mt-5">
            <button type="submit" class="btn primary t-white">Enregistrer</button>
        </div>
    </form> -->
{% endblock %}