eatsj_web/api/urls.py
from django.urls import path
# from rest_framework.authtoken import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

from .views import UserRecordView


app_name = 'api'

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_refresh'),
    path('user/', UserRecordView.as_view(), name='users'),
]

eatsj_web/eatsj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('web.urls')),
    path('api/', include('api.urls')),
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

eatsj_web/web/urls.py
from django.urls import path, include

from . import views


app_name = "eatsj"


urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('leaderboard', views.LeaderboardView.as_view(), name="leaderboard"),
    path('histories', views.HistoriesListView.as_view(), name="history_list"),

    path('auth/', include([
        path('account/', views.AccountView.as_view(), name='account'),
        path('signin/', views.SigninView.as_view(), name="signin"),
        path('signout/', views.signout, name="signout"),
    ])),

    path('users/', include([
        path('', views.UserListView.as_view(), name="user_list"),
        path('save/', views.UserCreateView.as_view(), name="user_create"),
        path('<pk>/details/', views.UserDetailsView.as_view(), name="user_details"),
        path('<pk>/delete/', views.user_delete_view, name="user_delete"),
    ])),

    path('products/', include([
        path('menus/', include([
            path('', views.ProductsMenuListView.as_view(), name="products_menu_list"),
            path('save/', views.ProductsMenuCreateView.as_view(), name="products_menu_create"),
        ])),
        path('foods/', include([
            path('', views.ProductsFoodListView.as_view(), name="products_food_list"),
            path('save/', views.ProductsFoodCreateView.as_view(), name="products_food_create"),
            path('<pk>/details/', views.ProductsFoodDetailsView.as_view(), name="products_food_details"),
            path('<pk>/delete/', views.product_food_delete_view, name="products_food_delete"),
        ])),
        path('drinks/', include([
            path('', views.ProductsDrinkListView.as_view(), name="products_drink_list"),
            path('save/', views.ProductsDrinkCreateView.as_view(), name="products_drink_create"),
            path('<pk>/details/', views.ProductsDrinkDetailsView.as_view(), name="products_drink_details"),
            path('<pk>/delete/', views.product_drink_delete_view, name="products_drink_delete"),
        ])),
    ])),

    path('orders/', include([
        path('', views.OrdersListView.as_view(), name="order_list")
    ])),

]

eatsj_web/web/templates/shared/_breadcrumb.html
<nav class="breadcrumb light t-primary">
    <ul>
        {% if current == 'products' %}
            <li><a href="{% url 'eatsj:products_menu_list' %}">Produits</a></li>

            {% if title == 'foods' %}
                <li class="active"><a href="{% url 'eatsj:products_food_list' %}">Plats</a></li>
            {% elif title == 'foods_create' %}
                <li><a href="{% url 'eatsj:products_food_list' %}">Plats</a></li>
                <li class="active"><a href="{% url 'eatsj:products_food_create' %}">Ajout</a></li>
            {% elif title == 'foods_details' %}
                <li><a href="{% url 'eatsj:products_food_list' %}">Plats</a></li>
                <li class="active"><a href="{% url 'eatsj:products_food_details' pk=object.pk %}">Détails</a></li>

            {% elif title == 'drinks' %}
                <li class="active"><a href="{% url 'eatsj:products_drink_list' %}">Boissons</a></li>
            {% elif title == 'drinks_create' %}
                <li><a href="{% url 'eatsj:products_drink_list' %}">Boissons</a></li>
                <li class="active"><a href="{% url 'eatsj:products_drink_create' %}">Ajout</a></li>
            {% elif title == 'drinks_details' %}
                <li><a href="{% url 'eatsj:products_drink_list' %}">Boissons</a></li>
                <li class="active"><a href="{% url 'eatsj:products_drink_details' pk=object.pk %}">Détails</a></li>
            
            {% elif title == 'menus_create' %}
                <li><a href="{% url 'eatsj:products_menu_list' %}">Menus</a></li>
                <li class="active"><a href="{% url 'eatsj:products_menu_create' %}">Ajout menu du jour</a></li>
            {% else %}
                <li class="active"><a href="{% url 'eatsj:products_menu_list' %}">Menus</a></li>
            {% endif %}
        {% elif current == 'users' %}
            <li class="{% if not title %}active{% endif %}"><a href="{% url 'eatsj:user_list' %}">Utilisateurs</a></li>

            {% if title == 'create' %}
                <li class="active"><a href="{% url 'eatsj:user_create' %}">Ajout</a></li>
            {% elif title == 'details' %}
                <li class="active"><a href="{% url 'eatsj:user_details' pk=object.pk %}">Détails</a></li>
            {% endif %}
                        
        {% elif current == 'orders' %}
            <li class="active"><a href="{% url 'eatsj:order_list' %}">Commandes</a></li>
        {% elif current == 'histories' %}
            <li class="active"><a href="{% url 'eatsj:history_list' %}">Historique</a></li>
        {% else %}
            <li><a href="{% url 'eatsj:home' %}">Accueil</a></li>
            
            {% if title|default:'dashboard' == 'dashboard' %}
                <li class="active"><a href="{% url 'eatsj:home' %}">Dashboard</a></li>
            {% else %}
                <li class="active"><a href="{% url 'eatsj:home' %}">Leaderboard</a></li>
            {% endif %}
                
        {% endif %}
            
    </ul>
</nav>

eatsj_web/web/templates/shared/_css.html
{% load static %}

<link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/slim.min.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">

eatsj_web/web/templates/shared/_css_importfile.html
<link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">

eatsj_web/web/templates/shared/_footer.html
<footer class="px-5 py-2 t-warning">
    <span>&COPY; 2020-2021</span><br>
    <span>Institut Saint-Jean</span>
</footer>

eatsj_web/web/templates/shared/_js.html
{% load static %}

<script src="{% static '/js/main.js' %}" defer></script>

eatsj_web/web/templates/shared/_js_importfile.html
<script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-resize/dist/filepond-plugin-image-resize.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-crop/dist/filepond-plugin-image-crop.js"></script>
<script src="https://unpkg.com/filepond/dist/filepond.js"></script>

eatsj_web/web/templates/shared/_sidebar.html
{% load static %}

<nav class="sidebar col row gap-0 flex-col bg-secondary">
    <a class="sidebar-brand no-style group pt-4 pb-2 h3 t-white">
        <img src="{% static 'img/logo-white.svg' %}" alt="logo">
        <span>eat'sj</span>
    </a>

    <hr class="divider"><br>

    <ul class="col side-link white mt-4 t-white">
        <li class="{% if title|default:'home' == 'home' %}active{% endif %}">
            <a href="{% url 'eatsj:home' %}">
                <i class="material-icons">home</i>
                <span class="ml-1">Accueil</span>
            </a>
        </li>
        <li class="{% if title == 'orders' %}active{% endif %}">
            <a href="{% url 'eatsj:order_list' %}">
                <i class="material-icons">shopping_cart</i>
                <span class="ml-1">Commandes</span>
            </a>
        </li>
        <li class="{% if title == 'products' %} active {% endif %}">
            <a href="{% url 'eatsj:products_menu_list' %}">
                <i class="material-icons">restaurant_menu</i>
                <span class="ml-1">Produits</span>
            </a>
        </li>
        <li class="{% if title == 'users' %}active{% endif %}">
            <a href="{% url 'eatsj:user_list' %}">
                <i class="material-icons">people</i>
                <span class="ml-1">Utilisateurs</span>
            </a>
        </li>
        <li class="{% if title == 'histories' %}active{% endif %}">
            <a href="{% url 'eatsj:history_list' %}">
                <span class="material-icons">history</span>
                <span class="ml-1">Historiques</span>
            </a>
        </li>
    </ul>

    <br><hr class="divider"><br>

    <ul class="side-link white t-white">
        <li class="{% if title == 'account' %}active{% endif %}"><a href="{% url 'eatsj:account' %}">Compte</a></li>
        <li><a href="{% url 'eatsj:signout' %}">Déconnexion</a></li>
    </ul>

    <br>
    {% include 'shared/_footer.html' %}
</nav>

eatsj_web/web/templates/shared/_topbar.html
{% load static %}

{% comment %}
<nav class="nav white shadow-2 t-primary">
    <a href="{% url 'eatsj:home' %}" class="nav-brand no-style group py-1">
        <img src="{% static 'img/logo.svg' %}" alt="logo" style="width: 60px;">
        <span class="h3 t-primary">eat'sj</span>
    </a>
    <ul class="nav-link-right">
        <li class="nav-item"><a href="#">{{ request.user.username }}</a></li>
        <li class="nav-item"><a href="{% url 'eatsj:signout' %}">déconnexion</a></li>
    </ul>
</nav> 
{% endcomment %}
    

<nav class="topbar nav transparent t-grey shadow-1 px-5">
    <ul class="nav-link no-style">
        {% if current == 'home' %}
            <li class="nav-item {% if title == 'dashboard' %} active {% endif %}"><a class="py-4" href="{% url 'eatsj:home' %}">Dashboard</a></li>
            <li class="nav-item {% if title == 'leaderboard' %} active {% endif %}"><a class="py-4" href="{% url 'eatsj:leaderboard' %}">Leaderboard</a></li>
        {% elif current == 'products' %}
            <li class="nav-item {% if title == 'products_menu' %} active {% endif %}"><a class="py-4" href="{% url 'eatsj:products_menu_list' %}">Menus</a></li>
            <li class="nav-item {% if title == 'products_food' %} active {% endif %}"><a class="py-4" href="{% url 'eatsj:products_food_list' %}">Plats</a></li>
            <li class="nav-item {% if title == 'products_drink' %} active {% endif %}"><a class="py-4" href="{% url 'eatsj:products_drink_list' %}">Boissons</a></li>
            <!-- <li class="nav-item {% if title == 'products_drink' %} active {% endif %}"><a class="py-4" href="{% url 'eatsj:products_drink_list' %}">Formules</a></li> -->
        {% else %}

        {% endif %}
    </ul>
    <ul class="nav-link-right no-style">
        <li class="nav-item dropdown">
            <a class="py-4" href="#"><i class="material-icons">notifications</i></a>
            <ul class="no-style dropdown-content">
                <li>Msg 1</li>
                <li>Msg 2</li>
                <li>Msg 3</li>
            </ul>
        </li>
        <li class="nav-item">
            <a class="py-4" href="#">
                <i class="material-icons">face</i>
                <span class="ml-1">{{ request.user.username }}</span></a>
            </li>
    </ul>
</nav>