eatsj_web/api/urls.py
from django.urls import path
# from rest_framework.authtoken import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

from .views import UserRecordView


app_name = 'api'

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_refresh'),
    path('user/', UserRecordView.as_view(), name='users'),
]

eatsj_web/eatsj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('web.urls')),
    path('api/', include('api.urls')),
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

eatsj_web/web/urls.py
from django.urls import path, include

from . import views


app_name = "eatsj"


urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('leaderboard', views.LeaderboardView.as_view(), name="leaderboard"),
    path('histories', views.HistoriesListView.as_view(), name="history_list"),

    path('auth/', include([
        path('account/', views.AccountView.as_view(), name='account'),
        path('signin/', views.SigninView.as_view(), name="signin"),
        path('signout/', views.signout, name="signout"),
    ])),

    path('users/', include([
        path('', views.UserListView.as_view(), name="user_list"),
        path('save/', views.UserCreateView.as_view(), name="user_create"),
        path('<pk>/details/', views.UserDetailsView.as_view(), name="user_details"),
        path('<pk>/delete/', views.user_delete_view, name="user_delete"),
    ])),

    path('products/', include([
        path('menus/', include([
            path('', views.ProductsMenuListView.as_view(), name="products_menu_list"),
            path('save/', views.ProductsMenuCreateView.as_view(), name="products_menu_create"),
        ])),
        path('foods/', include([
            path('', views.ProductsFoodListView.as_view(), name="products_food_list"),
            path('save/', views.ProductsFoodCreateView.as_view(), name="products_food_create"),
            path('<pk>/details/', views.ProductsFoodDetailsView.as_view(), name="products_food_details"),
            path('<pk>/delete/', views.product_food_delete_view, name="products_food_delete"),
        ])),
        path('drinks/', include([
            path('', views.ProductsDrinkListView.as_view(), name="products_drink_list"),
            path('save/', views.ProductsDrinkCreateView.as_view(), name="products_drink_create"),
            path('<pk>/details/', views.ProductsDrinkDetailsView.as_view(), name="products_drink_details"),
            path('<pk>/delete/', views.product_drink_delete_view, name="products_drink_delete"),
        ])),
    ])),

    path('orders/', include([
        path('', views.OrdersListView.as_view(), name="order_list")
    ])),

]

eatsj_web/web/templates/pages/users/user_create.html
{% extends 'layouts/__app.html' %}

{% block title %} Ajout Utilisateur {% endblock %}

{% block sidebar %} {% include 'shared/_sidebar.html' with title="users" %} {% endblock %}

{% block breadcrumb %} {% include 'shared/_breadcrumb.html' with current='users' title='create' %} {% endblock breadcrumb %}

{% block main %}
    <h1 class="h2">Ajouter un nouveau utilisateur</h1>


    <form class="t-grey" method="POST">
        {% csrf_token %}

        
        {% if form.errors %}
            <div class="alert warning mb-5">
                <div>
                    {{ form.errors }}
                </div>
                <!-- {% for error in form.errors %}
                    <div>{{ error }}</div>
                {% endfor %} -->
            </div>
        {% endif %}


        <div class="grid of-2 gap-3 mt-5">
            <div class="cell field">
                {{form.last_name}}
                <div class="field-label">
                    <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.first_name}}
                <div class="field-label">
                    <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.register}}
                <div class="field-label">
                    <label for="{{ form.register.id_for_label }}">{{ form.register.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                <div class="field-select">
                    {{form.gender}}
                </div>
                <div class="field-label">
                    <label for="{{ form.gender.id_for_label }}">{{ form.gender.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.phone}}
                <div class="field-label">
                    <label for="{{ form.phone.id_for_label }}">{{ form.phone.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.email}}
                <div class="field-label">
                    <label for="{{ form.email.id_for_label }}">{{ form.email.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.username}}
                <div class="field-label">
                    <label for="{{ form.username.id_for_label }}">{{ form.username.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.is_superuser}}
                <div class="field-label">
                    <label for="{{ form.is_superuser.id_for_label }}">{{ form.is_superuser.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.password}}
                <div class="field-label">
                    <label for="{{ form.password.id_for_label }}">{{ form.password.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.confirm_password}}
                <div class="field-label">
                    <label for="{{ form.confirm_password.id_for_label }}">{{ form.confirm_password.label_tag }}</label>
                </div>
            </div>
        </div>

        <div class="text-center mt-5">
            <button type="submit" class="btn primary t-white">Enregistrer</button>
        </div>
    </form>
{% endblock %}

eatsj_web/web/templates/pages/users/user_details.html
{% extends 'layouts/__app.html' %}

{% block title %} Utilisateurs {% endblock %}

{% block sidebar %} {% include 'shared/_sidebar.html' with title="users" %} {% endblock %}

{% block breadcrumb %} {% include 'shared/_breadcrumb.html' with current='users' title='details' %} {% endblock breadcrumb %}

{% block main %}
    <h1 class="h2">Détails de {{ object.username }}</h1>


    <form class="t-grey">

        <div class="grid of-2 gap-3 mt-5">
            <div class="cell field">
                {{form.last_name}}
                <div class="field-label">
                    <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.first_name}}
                <div class="field-label">
                    <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.register}}
                <div class="field-label">
                    <label for="{{ form.register.id_for_label }}">{{ form.register.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                <div class="field-select">
                    {{form.gender}}
                </div>
                <div class="field-label">
                    <label for="{{ form.gender.id_for_label }}">{{ form.gender.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.phone}}
                <div class="field-label">
                    <label for="{{ form.phone.id_for_label }}">{{ form.phone.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.email}}
                <div class="field-label">
                    <label for="{{ form.email.id_for_label }}">{{ form.email.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.username}}
                <div class="field-label">
                    <label for="{{ form.username.id_for_label }}">{{ form.username.label_tag }}</label>
                </div>
            </div>
            <div class="cell field">
                {{form.is_superuser}}
                <div class="field-label">
                    <label for="{{ form.is_superuser.id_for_label }}">{{ form.is_superuser.label_tag }}</label>
                </div>
            </div>
        </div>

        <div class="text-center mt-5">
            <div class="group">
                <button type="button" class="btn info link">Cliquez ici pour modifier</button>
                <button type="submit" class="btn primary t-white" disabled>Modifier</button>
            </div>
        </div>
    </form>
{% endblock %}

eatsj_web/web/templates/pages/users/users.html
{% extends 'layouts/__app.html' %}

{% block title %} Utilisateurs {% endblock %}

{% block sidebar %} {% include 'shared/_sidebar.html' with title="users" %} {% endblock %}

{% block breadcrumb %} {% include 'shared/_breadcrumb.html' with current='users' %} {% endblock breadcrumb %}

{% block main %}
    <div class="row">
        <div class="col">
            <h1 class="h2">Utilisateurs</h1>
        </div>
        <div class="col text-right">
            <a href="{% url 'eatsj:user_create' %}" class="btn primary">
                <span class="icon">
                    <i class="material-icons">add</i>
                </span>&nbsp;
                <span>Ajouter</span>
            </a>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table centered striped">
            <thead class="bg-secondary t-white">
                <tr>
                    <th>Matricule</th>
                    <th>Nom complet</th>
                    <th>Sexe</th>
                    <th>Email</th>
                    <th>Téléphone</th>
                    <th>Est manager</th>
                    <th>État</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for user in object_list %}
                    <tr>
                        <td>{{ user.register }}</td>
                        <td>{{ user.last_name }} {{ user.first_name }}</td>
                        <td>{{ user.gender }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.phone }}</td>
                        <td>
                            {% if user.staff or user.is_superuser %}
                                oui
                            {% else %}
                                non
                            {% endif %}
                        </td>
                        <td>actif</td>
                        <td>
                            <div class="group">
                                <a href="{% url 'eatsj:user_delete' pk=user.pk %}" class="btn danger link size-sm">Supprimer</a>
                                <a href="{% url 'eatsj:user_details' pk=user.pk %}" class="btn info size-sm">Details</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


    <!-- <form action="" class="t-grey">
        
        {% for field in form %}
            <div class="field">
                {{ field }}

                <div class="field-label">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
            </div>
        {% endfor %}

        <button type="submit" class="btn primary t-white">Enregistrer</button>
    </form> -->
{% endblock %}